apiVersion: v1
kind: Service
metadata:
  name: result-backend
  namespace: results
spec:
  type: NodePort
  selector:
    app: result-backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
