apiVersion: v1
kind: Service
metadata:
  name: result-frontend
  namespace: results
spec:
  type: NodePort
  selector:
    app: result-frontend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32080
